# Generated by Django 3.1 on 2020-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megatest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
